//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POB.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("opbNome")]
        public string opbNome {
            get {
                return ((string)(this["opbNome"]));
            }
            set {
                this["opbNome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string opbNomeIFCPilar {
            get {
                return ((string)(this["opbNomeIFCPilar"]));
            }
            set {
                this["opbNomeIFCPilar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string obpNomeIFCViga {
            get {
                return ((string)(this["obpNomeIFCViga"]));
            }
            set {
                this["obpNomeIFCViga"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string opbNomeIFCLaje {
            get {
                return ((string)(this["opbNomeIFCLaje"]));
            }
            set {
                this["opbNomeIFCLaje"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Contrutivel")]
        public string nomePainelFerramentaModelagem {
            get {
                return ((string)(this["nomePainelFerramentaModelagem"]));
            }
            set {
                this["nomePainelFerramentaModelagem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Estrutura")]
        public string nomeAbaEstrutura {
            get {
                return ((string)(this["nomeAbaEstrutura"]));
            }
            set {
                this["nomeAbaEstrutura"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Descrição do Insumo")]
        public string L7InsumoVinculado {
            get {
                return ((string)(this["L7InsumoVinculado"]));
            }
            set {
                this["L7InsumoVinculado"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Marca")]
        public string Mark {
            get {
                return ((string)(this["Mark"]));
            }
            set {
                this["Mark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Volume")]
        public string Volume {
            get {
                return ((string)(this["Volume"]));
            }
            set {
                this["Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comentários")]
        public string Comments {
            get {
                return ((string)(this["Comments"]));
            }
            set {
                this["Comments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Área")]
        public string Area {
            get {
                return ((string)(this["Area"]));
            }
            set {
                this["Area"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Espessura")]
        public string Thickness {
            get {
                return ((string)(this["Thickness"]));
            }
            set {
                this["Thickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Diâmetro")]
        public string Diameter {
            get {
                return ((string)(this["Diameter"]));
            }
            set {
                this["Diameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tipo de sistema")]
        public string systemType {
            get {
                return ((string)(this["systemType"]));
            }
            set {
                this["systemType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Elevação")]
        public string Elevation {
            get {
                return ((string)(this["Elevation"]));
            }
            set {
                this["Elevation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pilares estruturais")]
        public string structuralColumns {
            get {
                return ((string)(this["structuralColumns"]));
            }
            set {
                this["structuralColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unidade do insumo")]
        public string L7Unidade {
            get {
                return ((string)(this["L7Unidade"]));
            }
            set {
                this["L7Unidade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comprimento do insumo")]
        public string L7Comprimento {
            get {
                return ((string)(this["L7Comprimento"]));
            }
            set {
                this["L7Comprimento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Material")]
        public string Material {
            get {
                return ((string)(this["Material"]));
            }
            set {
                this["Material"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Paredes")]
        public string walls {
            get {
                return ((string)(this["walls"]));
            }
            set {
                this["walls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peças")]
        public string parts {
            get {
                return ((string)(this["parts"]));
            }
            set {
                this["parts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Colunas")]
        public string Columns {
            get {
                return ((string)(this["Columns"]));
            }
            set {
                this["Columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Quadro estrutural")]
        public string structuralFraming {
            get {
                return ((string)(this["structuralFraming"]));
            }
            set {
                this["structuralFraming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Treliças estruturais")]
        public string structuralTrusses {
            get {
                return ((string)(this["structuralTrusses"]));
            }
            set {
                this["structuralTrusses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Telhados")]
        public string telhados {
            get {
                return ((string)(this["telhados"]));
            }
            set {
                this["telhados"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pisos")]
        public string floors {
            get {
                return ((string)(this["floors"]));
            }
            set {
                this["floors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Forros")]
        public string forros {
            get {
                return ((string)(this["forros"]));
            }
            set {
                this["forros"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mobiliário")]
        public string furniture {
            get {
                return ((string)(this["furniture"]));
            }
            set {
                this["furniture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Modelos genéricos")]
        public string genericModels {
            get {
                return ((string)(this["genericModels"]));
            }
            set {
                this["genericModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Guarda-corpos")]
        public string GuardaCorpos {
            get {
                return ((string)(this["GuardaCorpos"]));
            }
            set {
                this["GuardaCorpos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Janelas")]
        public string Janelas {
            get {
                return ((string)(this["Janelas"]));
            }
            set {
                this["Janelas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tubulação flexível")]
        public string flexPipes {
            get {
                return ((string)(this["flexPipes"]));
            }
            set {
                this["flexPipes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Escadas")]
        public string escadas {
            get {
                return ((string)(this["escadas"]));
            }
            set {
                this["escadas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Equipamento especial")]
        public string equipamentoEspecial {
            get {
                return ((string)(this["equipamentoEspecial"]));
            }
            set {
                this["equipamentoEspecial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Equipamento elétrico")]
        public string electricalFixtures {
            get {
                return ((string)(this["electricalFixtures"]));
            }
            set {
                this["electricalFixtures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tubulação")]
        public string pipes {
            get {
                return ((string)(this["pipes"]));
            }
            set {
                this["pipes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conexões de tubo")]
        public string pipeFittings {
            get {
                return ((string)(this["pipeFittings"]));
            }
            set {
                this["pipeFittings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Acessórios do tubo")]
        public string pipeAccessories {
            get {
                return ((string)(this["pipeAccessories"]));
            }
            set {
                this["pipeAccessories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Equipamentos hidráulicos")]
        public string plumbingFixtures {
            get {
                return ((string)(this["plumbingFixtures"]));
            }
            set {
                this["plumbingFixtures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sprinklers")]
        public string Sprinklers {
            get {
                return ((string)(this["Sprinklers"]));
            }
            set {
                this["Sprinklers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Equipamento mecânico")]
        public string mechanicalEquipament {
            get {
                return ((string)(this["mechanicalEquipament"]));
            }
            set {
                this["mechanicalEquipament"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GrossWeigth")]
        public string GrossWeigth {
            get {
                return ((string)(this["GrossWeigth"]));
            }
            set {
                this["GrossWeigth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chapa")]
        public string tocChapa {
            get {
                return ((string)(this["tocChapa"]));
            }
            set {
                this["tocChapa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Densidade de área")]
        public string tocDensidadeChapa {
            get {
                return ((string)(this["tocDensidadeChapa"]));
            }
            set {
                this["tocDensidadeChapa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0004121A")]
        public string handleAta {
            get {
                return ((string)(this["handleAta"]));
            }
            set {
                this["handleAta"] = value;
            }
        }
    }
}
